name: gg_timeline
description: GgTimeline allows you to manage arbitrary data like on a timeline.
version: 1.0.0+beta.2
homepage: https://github.com/inlavigo/gg_timeline

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  gg_typedefs: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  flutter_lints: ^2.0.1
